[package]
name = "cgt-formatter-plain"
version.workspace = true
edition.workspace = true

[dependencies]
cgt-core = { path = "../cgt-core" }
cgt-format = { path = "../cgt-format" }
rust_decimal = "1"
chrono = "0.4"

[lints]
workspace = true
