[package]
name = "cgt-formatter-plain"
version = "0.1.0"
edition = "2024"

[dependencies]
cgt-core = { path = "../cgt-core" }
cgt-format = { path = "../cgt-format" }
rust_decimal = "1"
chrono = "0.4"

[lints]
workspace = true
