[package]
name = "cgt-formatter-pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
cgt-core = { path = "../cgt-core" }
rust_decimal = "1"
chrono = "0.4"
iso_currency = "0.4"
typst = "0.14"
typst-as-lib = "0.15"
typst-pdf = "0.14"

[lints]
workspace = true
